version: "3.9"

services:
  # 1. PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_bookbridge
    environment:
      POSTGRES_USER: bookbridge_userservice
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bookbridge_userservice"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. UserService
  userservice:
    build:
      context: .
      dockerfile: UserService.Api/Dockerfile
    container_name: bookbridge_userservice
    environment:
      ConnectionStrings__UserServiceConnection: Host=db;Port=5432;Database=user_service;Username=bookbridge_userservice;Password=12345;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5141:8080"
    depends_on:
      db:
        condition: service_healthy

  # 3. BookService
  bookservice:
    build:
      context: .
      dockerfile: BookService.Api/Dockerfile
    container_name: bookbridge_bookservice
    environment:
      ConnectionStrings__BookServiceConnection: Host=db;Port=5432;Database=book_service;Username=bookbridge_userservice;Password=12345;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5142:8080"
    depends_on:
      db:
        condition: service_healthy

  # 4. BookStoreService
  bookstoreservice:
    build:
      context: .
      dockerfile: BookStoreService.Api/Dockerfile
    container_name: bookbridge_bookstoreservice
    environment:
      ConnectionStrings__BookStoreServiceConnection: Host=db;Port=5432;Database=bookstore_service;Username=bookbridge_userservice;Password=12345;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5143:8080"
    depends_on:
      db:
        condition: service_healthy

  # 5. OrderService
  orderservice:
    build:
      context: .
      dockerfile: OrderService.Api/Dockerfile
    container_name: bookbridge_orderservice
    environment:
      ConnectionStrings__OrderServiceConnection: Host=db;Port=5432;Database=order_service;Username=bookbridge_userservice;Password=12345;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5144:8080"
    depends_on:
      db:
        condition: service_healthy

  # 6. API Gateway
  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: bookbridge_gateway
    ports:
      - "5139:8080"
    depends_on:
      - userservice
      - bookservice
      - bookstoreservice
      - orderservice

  # 7. pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bookbridge
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
