services:
  # 1. PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_bookbridge
    environment:
      POSTGRES_USER: bookbridge_userservice
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bookbridge_userservice", "-d", "user_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. UserService
  userservice:
    build:
      context: .
      dockerfile: UserService.Api/Dockerfile
    container_name: bookbridge_userservice
    environment:
      ConnectionStrings__UserServiceConnection: Host=db;Port=5432;Database=user_service;Username=bookbridge_userservice;Password=12345;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5141:8080"
    depends_on:
      db:
        condition: service_healthy

  # 3. API Gateway
  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: bookbridge_gateway
    ports:
      - "5139:8080"
    depends_on:
      - userservice

  # 4. pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bookbridge
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Lưu lại cấu hình pgAdmi
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
